// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vote.proto

package vote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestVoteMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   int64                  `protobuf:"varint,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`                 // candidates term
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"` // index of candidates last log entry
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`   // term of candidate's last log entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteMsg) Reset() {
	*x = RequestVoteMsg{}
	mi := &file_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteMsg) ProtoMessage() {}

func (x *RequestVoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteMsg.ProtoReflect.Descriptor instead.
func (*RequestVoteMsg) Descriptor() ([]byte, []int) {
	return file_vote_proto_rawDescGZIP(), []int{0}
}

func (x *RequestVoteMsg) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteMsg) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteMsg) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteMsg) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

var File_vote_proto protoreflect.FileDescriptor

const file_vote_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"vote.proto\"\x8c\x01\n" +
	"\x0eRequestVoteMsg\x12 \n" +
	"\vcandidateId\x18\x01 \x01(\x03R\vcandidateId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm2@\n" +
	"\vVoteService\x121\n" +
	"\vRequestVote\x12\x0f.RequestVoteMsg\x1a\x0f.RequestVoteMsg\"\x00B!Z\x1fgithub.com/koss756/dkvStore/apib\x06proto3"

var (
	file_vote_proto_rawDescOnce sync.Once
	file_vote_proto_rawDescData []byte
)

func file_vote_proto_rawDescGZIP() []byte {
	file_vote_proto_rawDescOnce.Do(func() {
		file_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vote_proto_rawDesc), len(file_vote_proto_rawDesc)))
	})
	return file_vote_proto_rawDescData
}

var file_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vote_proto_goTypes = []any{
	(*RequestVoteMsg)(nil), // 0: RequestVoteMsg
}
var file_vote_proto_depIdxs = []int32{
	0, // 0: VoteService.RequestVote:input_type -> RequestVoteMsg
	0, // 1: VoteService.RequestVote:output_type -> RequestVoteMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vote_proto_init() }
func file_vote_proto_init() {
	if File_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vote_proto_rawDesc), len(file_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vote_proto_goTypes,
		DependencyIndexes: file_vote_proto_depIdxs,
		MessageInfos:      file_vote_proto_msgTypes,
	}.Build()
	File_vote_proto = out.File
	file_vote_proto_goTypes = nil
	file_vote_proto_depIdxs = nil
}
